//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pitchfork.TypeParsing.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pitchfork.TypeParsing.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the assembly name &apos;{0}&apos;..
        /// </summary>
        internal static string AssemblyId_CannotParseAssemblyFullName {
            get {
                return ResourceManager.GetString("AssemblyId_CannotParseAssemblyFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate token: &apos;{0}&apos;.
        /// </summary>
        internal static string Common_DuplicateToken {
            get {
                return ResourceManager.GetString("Common_DuplicateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The identifier &apos;{0}&apos; is not allowed..
        /// </summary>
        internal static string Common_IdentifierNotAllowed {
            get {
                return ResourceManager.GetString("Common_IdentifierNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-negative number needed..
        /// </summary>
        internal static string Common_NonNegativeNumberNeeded {
            get {
                return ResourceManager.GetString("Common_NonNegativeNumberNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank must be between 1 and 32, inclusive..
        /// </summary>
        internal static string Common_RankOutOfRange {
            get {
                return ResourceManager.GetString("Common_RankOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized token: &apos;{0}&apos;.
        /// </summary>
        internal static string Common_UnrecognizedToken {
            get {
                return ResourceManager.GetString("Common_UnrecognizedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input array must contain exactly 8 bytes..
        /// </summary>
        internal static string PublicKeyToken_CtorArrayInvalid {
            get {
                return ResourceManager.GetString("PublicKeyToken_CtorArrayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input string must contain exactly 16 hex characters..
        /// </summary>
        internal static string PublicKeyToken_CtorStringInvalid {
            get {
                return ResourceManager.GetString("PublicKeyToken_CtorStringInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum recursive depth of {0} exceeded..
        /// </summary>
        internal static string RecursionCheck_MaxDepthExceeded {
            get {
                return ResourceManager.GetString("RecursionCheck_MaxDepthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeGenericType cannot be called on non-elemental types..
        /// </summary>
        internal static string TypeId_CannotMakeGenericsFromNonElementalTypes {
            get {
                return ResourceManager.GetString("TypeId_CannotMakeGenericsFromNonElementalTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not allowed..
        /// </summary>
        internal static string TypeId_ExistingTypeNotAllowed {
            get {
                return ResourceManager.GetString("TypeId_ExistingTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM type &apos;{0}&apos; is not allowed..
        /// </summary>
        internal static string TypeId_ExistingTypeNotAllowed_NoComTypes {
            get {
                return ResourceManager.GetString("TypeId_ExistingTypeNotAllowed_NoComTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function pointer &apos;{0}&apos; is not allowed..
        /// </summary>
        internal static string TypeId_ExistingTypeNotAllowed_NoFunctionPointers {
            get {
                return ResourceManager.GetString("TypeId_ExistingTypeNotAllowed_NoFunctionPointers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic argument &apos;{0}&apos; is not allowed..
        /// </summary>
        internal static string TypeId_ExistingTypeNotAllowed_NoGenericArgs {
            get {
                return ResourceManager.GetString("TypeId_ExistingTypeNotAllowed_NoGenericArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can only be performed on constructed generic types..
        /// </summary>
        internal static string TypeId_InstanceIsNotAConstructedGenericType {
            get {
                return ResourceManager.GetString("TypeId_InstanceIsNotAConstructedGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can only be performed on array types..
        /// </summary>
        internal static string TypeId_InstanceIsNotAnArrayType {
            get {
                return ResourceManager.GetString("TypeId_InstanceIsNotAnArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type string specified..
        /// </summary>
        internal static string TypeId_InvalidTypeString {
            get {
                return ResourceManager.GetString("TypeId_InvalidTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type string specified: &apos;{0}&apos;.
        /// </summary>
        internal static string TypeId_InvalidTypeString_WithValue {
            get {
                return ResourceManager.GetString("TypeId_InvalidTypeString_WithValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is not allowed on managed pointer types..
        /// </summary>
        internal static string TypeId_OperationNotAllowedOnByRefTypes {
            get {
                return ResourceManager.GetString("TypeId_OperationNotAllowedOnByRefTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot make a {0}-arity generic type. Underlying type &apos;{1}&apos; does not have correct arity markers..
        /// </summary>
        internal static string TypeId_TypeNameDoesNotHaveCorrectAritySuffix {
            get {
                return ResourceManager.GetString("TypeId_TypeNameDoesNotHaveCorrectAritySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type &apos;{0}&apos; seen. Expected array type..
        /// </summary>
        internal static string TypeIdVisitor_UnexpectedType_ExpectedArrayType {
            get {
                return ResourceManager.GetString("TypeIdVisitor_UnexpectedType_ExpectedArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type &apos;{0}&apos; seen. Expected constructed generic type..
        /// </summary>
        internal static string TypeIdVisitor_UnexpectedType_ExpectedConstructedGenericType {
            get {
                return ResourceManager.GetString("TypeIdVisitor_UnexpectedType_ExpectedConstructedGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type &apos;{0}&apos; seen. Expected elemental type..
        /// </summary>
        internal static string TypeIdVisitor_UnexpectedType_ExpectedElementalType {
            get {
                return ResourceManager.GetString("TypeIdVisitor_UnexpectedType_ExpectedElementalType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type &apos;{0}&apos; seen. Expected managed pointer type..
        /// </summary>
        internal static string TypeIdVisitor_UnexpectedType_ExpectedManagedPointerType {
            get {
                return ResourceManager.GetString("TypeIdVisitor_UnexpectedType_ExpectedManagedPointerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type &apos;{0}&apos; seen. Expected szarray type..
        /// </summary>
        internal static string TypeIdVisitor_UnexpectedType_ExpectedSzArrayType {
            get {
                return ResourceManager.GetString("TypeIdVisitor_UnexpectedType_ExpectedSzArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type &apos;{0}&apos; seen. Expected unmanaged pointer type..
        /// </summary>
        internal static string TypeIdVisitor_UnexpectedType_ExpectedUnmanagedPointerType {
            get {
                return ResourceManager.GetString("TypeIdVisitor_UnexpectedType_ExpectedUnmanagedPointerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type &apos;{0}&apos; seen. Expected variable-bound array type..
        /// </summary>
        internal static string TypeIdVisitor_UnexpectedType_ExpectedVariableBoundArrayType {
            get {
                return ResourceManager.GetString("TypeIdVisitor_UnexpectedType_ExpectedVariableBoundArrayType", resourceCulture);
            }
        }
    }
}
